// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enkbruxcmkkbsabrdgpg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVua2JydXhjbWtrYnNhYnJkZ3BnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NTY0NjgsImV4cCI6MjA2NjAzMjQ2OH0.aw-dG26YnPMZAA6qnImm1MeDSoEA3goqdjEL-txo_gM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);